### ISSUE TITLE
Question/Proposal: Point to localstack for all sls calls ?

### ISSUE THREAD

**Issue by aaronstaves** [localstack/serverless-localstack#23]
I've been fighting with this for the past hour or two, but is there any reason sls-localstack is reconfiguring sls to point to localstack **only** for the `before:deploy:resources` hook ?  As seen here - https://github.com/localstack/serverless-localstack/blob/master/src/index.js#L26

If we're using serverless-localstack, any reason why we wouldn't want to enable it for **every** request ? Something similar to this - 
https://github.com/aaronstaves/serverless-localstack/commit/669c71c5bff369d6557889a8de0c893ec802efa9

**Comment by nealeu** [comment]
What good timing.  I've just hit the same but just added `before:invoke:invoke` as I wanted to use `sls invoke`.

**Comment by aaronstaves** [comment]
`sls invoke` is actually what led me to this as well, and I solved it by also adding `before:invoke:invoke`. 
 But then trying to run other commands (i.e. `sls info`), I was having to hunt down all the hook names and add them in.

If there isn't any issue with reconfiguring the endpoints anytime sls-localstack is used, I can certainly make a PR.  I'm just wondering why `before:deploy:resources` was the only hook sls-localstack was using, and was there a specific reason behind it?

**Comment by whummer** [comment]
@aaronstaves @nealeu Please see the following PR which partially reverts and slightly reimplements the in logic added in #24, due to async code required upon initialization of the plugin: https://github.com/localstack/serverless-localstack/pull/26

Please check out the latest version and report here if your use case is not covered - specifically, if you need to enable the plugin for a lifecycle event that does *not* start with `before:...`
